"""Add Centre and Group models

Revision ID: 0a17d2e661fd
Revises: 
Create Date: 2025-12-03 10:45:47.839085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a17d2e661fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_centres_id'), 'centres', ['id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('access', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('centre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enquiry_date', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('alternate_contact_details', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('email_reference', sa.String(), nullable=True),
    sa.Column('quote_reference', sa.String(), nullable=True),
    sa.Column('quote_description', sa.String(), nullable=True),
    sa.Column('quote_date', sa.String(), nullable=True),
    sa.Column('quote_amount', sa.String(), nullable=True),
    sa.Column('revised/negotiated', sa.String(), nullable=True),
    sa.Column('revised/negotiated_quote_date', sa.String(), nullable=True),
    sa.Column('revised/negotiated_quote_amount', sa.String(), nullable=True),
    sa.Column('quotation_given_by_name', sa.String(), nullable=True),
    sa.Column('quotation_given_by_department', sa.String(), nullable=True),
    sa.Column('project_number', sa.String(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('key_deliverables', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('order_date', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('extended_delivery_date', sa.String(), nullable=True),
    sa.Column('date_of_actual_commencement', sa.String(), nullable=True),
    sa.Column('order_value', sa.String(), nullable=True),
    sa.Column('details_of_external_internal_review_meeting', sa.String(), nullable=True),
    sa.Column('project_co_ordinator', sa.String(), nullable=True),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('co_ordinator_remarks', sa.String(), nullable=True),
    sa.Column('closer_report', sa.String(), nullable=True),
    sa.Column('technical_completed_year', sa.String(), nullable=True),
    sa.Column('financial_completed_year', sa.String(), nullable=True),
    sa.Column('dispatch_date', sa.String(), nullable=True),
    sa.Column('ppm_remarks', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.String(), nullable=True),
    sa.Column('get_amount', sa.String(), nullable=True),
    sa.Column('amount_claimed', sa.String(), nullable=True),
    sa.Column('amount_recieved', sa.String(), nullable=True),
    sa.Column('recieved_date', sa.String(), nullable=True),
    sa.Column('tds', sa.String(), nullable=True),
    sa.Column('get_tds', sa.String(), nullable=True),
    sa.Column('ld', sa.String(), nullable=True),
    sa.Column('bal', sa.String(), nullable=True),
    sa.Column('follow_up_status', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_centres_id'), table_name='centres')
    op.drop_table('centres')
    # ### end Alembic commands ###
